//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitHouse.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitHouse.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Not Found.
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Item Description.
        /// </summary>
        public static string EmptyItemDescription {
            get {
                return ResourceManager.GetString("EmptyItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Item Name.
        /// </summary>
        public static string EmptyItemName {
            get {
                return ResourceManager.GetString("EmptyItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Deleted.
        /// </summary>
        public static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Is Not Translated.
        /// </summary>
        public static string ItemIsNotTranslated {
            get {
                return ResourceManager.GetString("ItemIsNotTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name Exceed Length.
        /// </summary>
        public static string ItemNameExceedLength {
            get {
                return ResourceManager.GetString("ItemNameExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Not Found.
        /// </summary>
        public static string ItemNotFound {
            get {
                return ResourceManager.GetString("ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Is Already Exist.
        /// </summary>
        public static string MailExist {
            get {
                return ResourceManager.GetString("MailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Has No Items.
        /// </summary>
        public static string MealHasNoItems {
            get {
                return ResourceManager.GetString("MealHasNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Name Exceed Length.
        /// </summary>
        public static string MenuNameExceedLength {
            get {
                return ResourceManager.GetString("MenuNameExceedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Is Exist.
        /// </summary>
        public static string NameIsExist {
            get {
                return ResourceManager.GetString("NameIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is expired, please contact your admin..
        /// </summary>
        public static string PackageExpired {
            get {
                return ResourceManager.GetString("PackageExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not active, please contact your admin..
        /// </summary>
        public static string PackageNotActivated {
            get {
                return ResourceManager.GetString("PackageNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Is Already Exist.
        /// </summary>
        public static string PhoneExist {
            get {
                return ResourceManager.GetString("PhoneExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Not Found.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Not Found.
        /// </summary>
        public static string ProgramNotFound {
            get {
                return ResourceManager.GetString("ProgramNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Record Is Used In Another Module.
        /// </summary>
        public static string RecordIsUsedInAnotherModule {
            get {
                return ResourceManager.GetString("RecordIsUsedInAnotherModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSupported Language.
        /// </summary>
        public static string UnSupportedLanguage {
            get {
                return ResourceManager.GetString("UnSupportedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Is Disabled, Please contact to administrator.
        /// </summary>
        public static string YourAccountIsDisabled {
            get {
                return ResourceManager.GetString("YourAccountIsDisabled", resourceCulture);
            }
        }
    }
}
